### ISSUE TITLE
Remove the concept of the `PROJECT_ROOT`

### ISSUE THREAD

**Issue by csala** [HDI-Project/ATM#102]
No python code should have to rely on its location, so having to declare a `PROJECT_ROOT` variable in the main package is a sign of weak points in the project.

In any case, any path variables should be computed in the scripts that use the `atm` package, not within it.

**Comment by micahjsmith** [comment]
This goes hand-in-hand with an approach to rethink how configuration is supplied for the project.

Here is an example from Apache Airflow:
- The path to the configuration file and work directory is computed: https://github.com/apache/incubator-airflow/blob/master/airflow/configuration.py#L425
- The configuration file is read using ConfigParser https://github.com/apache/incubator-airflow/blob/master/airflow/configuration.py#L510
- Any application code that needs configuration variables (like data directory etc.) does `from atm import configuration as conf` and then `conf.get('DATA_DIR')`: https://github.com/apache/incubator-airflow/blob/master/airflow/settings.py#L35
