### ISSUE TITLE
Cleanup scripts folder and add them to lint

### ISSUE THREAD

**Issue by csala** [HDI-Project/ATM#106]
Review if there are scripts that are out of date and can be removed, and add the scripts folder to the lint commands.

**Comment by paulrich1234** [comment]
hi i donot know how to open the .model file to check the info of classifiers.looking forward to your replay.i will be apperate it .

**Comment by csala** [comment]
The scripts folder was removed altogether in the [0.1.1 relase](/HDI-Project/ATM/tree/v0.1.1), so this can be closed.
