### ISSUE TITLE
Database() initialization should treat DB path differently

### ISSUE THREAD

**Issue by RogerTangos** [HDI-Project/ATM#115]
Currently, db path is relative to the `Database()` caller. It should either be relative, or relative to the `Database.__class__.__file__` (not sure about my syntax there)

This confused me when I instantiated a database using the `sql.yaml` file, and the `db` instance kept creating and referencing an empty database. I didn't understand why it was empty and spent way too much time debugging a working `session`.

**Comment by micahjsmith** [comment]
Thanks for reporting. Where in the code are you finding this to occur?

**Comment by RogerTangos** [comment]
I'd actually totally forgotten about this until just now. I encountered this when working on the (unfinished) api, and since worked around it. I'm closing the ticket unless it comes up again (at which point, I'll just fix and submit a PR)
