### ISSUE TITLE
methods config should be configurable

### ISSUE THREAD

**Issue by kkarrancsu** [HDI-Project/ATM#13]
Line 7 of methods.py has the hardcoded value:
`CONFIG_PATH = 'methods'`

This should be moved to a configuration parameter by run_config.yaml

**Comment by bcyphers** [comment]
From my comment on #21: I think we want to leave these values out of the run config yaml. The run config is supposed to be logically linked to a datarun (which is machine-agnostic), and the output folders for models and metrics, if configurable, should be a machine-by-machine choice.

It might make sense to have model_dir and metric_dir be arguments to work() in worker.py.

**Comment by kkarrancsu** [comment]
Thanks, that makes sense.  I added new pull request #30 which takes your suggestions into account.

**Comment by bcyphers** [comment]
Closed with #30.

**Comment by bcyphers** [comment]
Closed with #30.
