### ISSUE TITLE
Remove demos folder and download them from S3

### ISSUE THREAD

**Issue by csala** [HDI-Project/ATM#144]
We now have an S3 bucket with tons of demo datasets, so the demos folder from within the project can be removed.

The `get_demos` function and CLI commands can be changed to behave like this:

* `get_demos`: returns a list of available demo datasets
* `download_demo`: gets a demo name as argument and downloads it into the `$(cwd)/demos` folder. Optionally get also the name of the destination folder.

**Comment by raam86** [comment]
would love to pick this up. 
what is the s3 bucket name?

**Comment by pvk-developer** [comment]
> would love to pick this up.
> what is the s3 bucket name?

Hello @raam86 , thank you for the interest and your will to contribute to the project. Unfortunately there is an actual [pull request](https://github.com/HDI-Project/ATM/pull/148) about this issue and it's on a pending review.

However if you would like to check some other issues or if you would like to implement some new feature, please feel free to ask for assignment or follow our [contributing guidelines](https://hdi-project.github.io/ATM/contributing.html) to open a new one.
