### ISSUE TITLE
atm/enter_data.py is failing: ImportError: No module named boto.s3.connection

### ISSUE THREAD

**Issue by ahgyger** [HDI-Project/ATM#15]
Got an issue when executing enter_data.py 

`atm) ahmets-MBP-782:atm ahmet$ python atm/enter_data.py
Traceback (most recent call last):
  File "atm/enter_data.py", line 7, in <module>
    from boto.s3.connection import S3Connection, Key as S3Key
ImportError: No module named boto.s3.connection
`

**Comment by ahgyger** [comment]
Fixed with : `pip install boto`
Should it be added to the requirement list?

**Comment by bcyphers** [comment]
Looks like a version is already in the requirements: 
`boto==2.48.0`
I wasn't able to repro the bug when trying with a fresh install on my machine. Are you using virtualenv + pip or something else?

**Comment by bcyphers** [comment]
Closed: can't reproduce
