### ISSUE TITLE
Installation and get started  is very confusing for Window ?

### ISSUE THREAD

**Issue by allaabdella2** [HDI-Project/ATM#160]
Please improve your installation process, it's very confusing for biggners. You should provide a content available to everyone and all the levels.

How to install and use this project in a simple steps in Windows? 
It says on my computer, it's successfully install by **pip install atm** , however, I can't run your example of getting started as it's very confusing and no clear starting point there.

I'm using featuretools and it's very easy to install and understand the get started procedure? 

Please help with that!

**Comment by micahjsmith** [comment]
I'm closing this issue as it is not actionable for us, however be assured that if we are able to reproduce the problems you report in #159 then we will investigate and fix.
