### ISSUE TITLE
How do you interpret the results across and within models?

### ISSUE THREAD

**Issue by schelian** [HDI-Project/ATM#18]
HI all, the log file will produce a line like below showing the best classifier and then you can find out the filename for the learner (provided you made a log of the run), but how do you read the model file?  The [manual](https://hdi-project.github.io/ATM/intro.html) doesn't seem to cover this either.

Examining results across all models (e.g., by a plot) would also be helpful.

```
nohup python atm/worker.py 2>&1 | tee Output.txt & # log the run

...
Saving model in: models/1261aa3655008f0b9afec119e25d5aab-b585ff5423b4c095b6562b81f2dc2f63-uniform__uniform.model
Saving metrics in: models/1261aa3655008f0b9afec119e25d5aab-b585ff5423b4c095b6562b81f2dc2f63-uniform__uniform.model
Saved classifier 21.
...
Best so far (learner 21): 0.716 +- 0.035
```

**Comment by bcyphers** [comment]
Good question. The docs are still catching up with the project at this point, so I'll try to help out on an issue-by-issue basis as we get those up to date. Making analysis and exploration more accessible is definitely something we'll be working on in the coming weeks.

Model files are serialized versions of the Model object saved with python's `joblib`.
For now, if you want to use a particular model, you can open up a python shell and do something like this:
```
>>> import joblib
>>> model = joblib.load('models/<MODELHASH>.model')
```
`model.pipeline` will store a trained [sklearn pipeline](http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html) that you can run on new data; you can also use `model.predict(X)` to use the model on fresh training data.

**Comment by schelian** [comment]
Thank you but I get a KeyError like below.  Version issues with the packages?  My pip list is also below.

```
gnumpy: failed to import cudamat. Using npmat instead. No GPU will be used.
Traceback (most recent call last):
  File "./fla/examine_model.py", line 6, in <module>
    model = joblib.load( MODEL_PATH + MODEL_FILENAME )
  File "/export/home/schelian1/prjs/autotuned_models/venv/local/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 578, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/export/home/schelian1/prjs/autotuned_models/venv/local/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 508, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '\x00'
```
pip list:
```
atm (0.0.1, /export/home/schelian1/prjs/autotuned_models)
boto (2.48.0)
btb (0.0.1, /export/home/schelian1/prjs/autotuned_models/venv/src/btb)
gdbn (0.1)
gnumpy (0.2)
joblib (0.11)
Lasagne (0.1)
MySQL-python (1.2.5)
nolearn (0.6.0)
numpy (1.13.1)
pandas (0.20.3)
pip (9.0.1)
python-dateutil (2.6.1)
pytz (2017.3)
PyYAML (3.12)
scikit-learn (0.18.2)
scipy (0.19.1)
setuptools (38.2.4)
six (1.11.0)
sklearn-pandas (1.5.0)
SQLAlchemy (1.1.14)
tabulate (0.8.2)
Theano (1.0.1)
wheel (0.30.0)

```

**Comment by bcyphers** [comment]
I think the line "`gnumpy: failed to import cudamat. Using npmat instead. No GPU will be used.`" is unrelated to your issue. I get that warning consistently as well, it does not affect the correctness of any of the code. 

Are you trying to open a model that was made with a version of the code before 
commit 635b4b62d5a2666079386d34891c132a746543a0 (pr #17)? That commit introduced some major changes to the model class, and the new class is incompatible with the old one. 

Have you tried creating, saving, and loading a model recently?

**Comment by schelian** [comment]
Cool, works with the latest.

Any parts of this task (logging, visualization, etc.) you want to doll out?  Seems related to #45 and #39 .
