### ISSUE TITLE
We need more docs!

### ISSUE THREAD

**Issue by bcyphers** [HDI-Project/ATM#19]
The documentation hasn't been updated for a few months, and does not reflect the state of the project. I'm removing the docs/ folder from the master repo for now, and pushing it into the branch 'bcyphers/docs' (#80) to avoid confusing newcomers to the project. The folder will be added back to master once it is closer to being ready.

**Comment by bcyphers** [comment]
A few docs have been added with #80, but there's a lot more to do to get full documentation coverage.

A few TODO's:
- A page which explains how to configure a datarun from top to bottom, including explanations of all the fields in each one of the config files and how the config files interact with command line args
- An explanation page for each major component of ATM, and a page that ties them all together. We kinda have one for the Modelhub (database.py), but need them for Worker and Model at least.
- Automatic documentation of all the public-facing API functions. That probably starts with model.py, enter_data.py, and worker.py.

**Comment by gducharme** [comment]
The Readme is now completely out of date. I'm on a Mac, so I don't know if the configuration is tuned to this Os.

After I copied the config from the git clone to the egg in the virtual env, and the data from OpenML, I got this, which looks like a mismatch between the run configuration and the pandas expectation.

```
File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: u'class'
```

I don't mind poor documentation, but at least having one known good path to get going would be great.

Is this easier to run in Linux? Or is there another preferred way?

**Comment by kveerama** [comment]
Did you download data from OpenML or use the one that is available [here](https://github.com/HDI-Project/ATM/blob/master/atm/data/test/pollution_1.csv) in the repo? While we point to the source data from OpenML, OpenML data does not name the target variable as 'class'.

**Comment by micahjsmith** [comment]
Hi @gducharme , I think this could be filed as a separate issue, thanks!

**Comment by gducharme** [comment]
Thanks, using the data from the project did the trick. I'm still not clear why I'm having to put in the data/templates and methods from the cloned repo into the venv egg.

**Comment by csala** [comment]
> I'm still not clear why I'm having to put in the data/templates and methods from the cloned repo into the venv egg.

@gducharme That's a consequence of a known issue: https://github.com/HDI-Project/ATM/issues/91
There is already a PR pending to be merged that fixes it.

**Comment by micahjsmith** [comment]
We've improved the documentation since this issue
