### ISSUE TITLE
ATM should be compatible with Python 2 and 3

### ISSUE THREAD

**Issue by bcyphers** [HDI-Project/ATM#35]
Thanks to @cclauss in #14 for bringing this up. We definitely want to future-proof ATM and make it as widely available as possible.

This is mostly a matter of sitting down and doing it. Most of it should be easy with [http://python-future.org/automatic_conversion.html](url). I think the biggest decision to make is [whether to use `unicode_literals` or not](http://python-future.org/unicode_literals.html).

I am for it. Since the project is new and volatile, it shouldn't matter too much whether we have to change the existing API, and I don't think there will be any major changes anyway. `unicode_literals` will result in cleaner code, and will make it easier to reason about strings in the future. 

I've started doing a test-run of `futurize` in BTB, since it's a much smaller project. Once that's done, I'll start going through file-by-file in ATM and doing the same. Feel free to jump in and contribute!

**Comment by cclauss** [comment]
See #36

**Comment by bcyphers** [comment]
Working on this in branch bcyphers/futurize
