### ISSUE TITLE
Create `explorer.py` to help explore results of Dataruns

### ISSUE THREAD

**Issue by bcyphers** [HDI-Project/ATM#45]
Should be a file that has helper methods for loading and testing previously-generated models. This should include some graphing and data visualization utilities.

Not sure about the best way to make the interface -- it could be a command-line tool like `enter_data` and `worker`, or it could be a Python REPL-style interface directly to the functions.

**Comment by schelian** [comment]
How is the ./atm.db database structured?  Walking through it would be a reasonable starting point for this.

**Comment by kveerama** [comment]
@schelian if you are looking to get started on creating explorer, we can share a doc where we are documenting some thoughts/ideas about what we could do- email me at kalyan@csail.mit.edu

**Comment by micahjsmith** [comment]
The ATMSeer project (https://github.com/HDI-Project/ATMSeer) has implemented an amazing visualization and administration interface.
