### ISSUE TITLE
Passing arguments for computation of ROC curves

### ISSUE THREAD

**Issue by kkarrancsu** [HDI-Project/ATM#48]
When the performance of a classifier is evaluated, the chain of function calls is as follows:

`worker.py::self.test_classifer` --> `model.train_test` --> `model.test_final_model` --> `metrics.py::test_pipeline` --> `metrics.py::get_metrics`

`test_pipeline` has a `kwargs` argument to allow for `include_curves` to be set, however, no `kwargs` are passed through the functions above the chain, so `include_curves` is always defaulted to `False` in the code.  How do we want to address this?  Should there be a command line argument (or configuration in run_config.yaml) which allows the user to decide if the roc_curves should be computed, and if so, passed through the system?

**Comment by bcyphers** [comment]
Good question. This is intentionally left out for now, because I wasn't sure the best way to deal with it. We're planning to overhaul metrics more later (and add custom metrics), so we'll probably address it then.

@kveerama what do you think? Config or command line argument?

**Comment by bcyphers** [comment]
I'm going to add it as a command-line argument to `worker.py` for now. However, I think it might be worth adding this to the config files and the database, as this will likely be a datarun-wide configuration.

**Comment by kkarrancsu** [comment]
Thanks! Please let me know how I can help with this as well, as I'm very interested in getting these outputs for my own work.

**Comment by bcyphers** [comment]
Partially addressed in #59
