### ISSUE TITLE
Make matplotlib a conditional import

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/ATM#5]
Tests fail because utilities.py is imported and matplotlib is in turn imported. Doesn't make any sense to have plotting as a hard dependency, but you can make it a conditional import in utilities.py

```
try:
    import matplotlib.pyplot as plt
except ImportError:
    plt = None

# then, in graph_series
if plt is None:
    raise ImportError("Unable to import matplotlib")
```

**Comment by bcyphers** [comment]
This is a good idea. If you want to make a pull request, I'll merge it.

**Comment by bcyphers** [comment]
Addressed in [https://github.com/HDI-Project/ATM/commit/b2945c13bf067481bbee7c2dd927ba1bad181a37](url)
