### ISSUE TITLE
is it possible to add more methods like RNN or CNN from keras? 

### ISSUE THREAD

**Issue by cici-tan** [HDI-Project/ATM#51]
Hi all, 

Just wonder is it possible if I want to use methods from keras to build CNN? Since there are all basic classifiers from sklearn in the methods for now. And does it accept 3d input?

**Comment by bcyphers** [comment]
It is definitely possible, but this is not one of our priorities right now.

If you would like to do it yourself, you can add a new classifier by creating a JSON file in the `methods/` directory using the same format as the other ones. If you want to add a CNN, you'll have to find a class that implements a CNN classifier with the scikit-learn `fit`/`transform` interface, then specify its hyperparameters in the same JSON format you find for the other methods.

We are working on a contributor guide that will go over this process in more detail, but you should go ahead and try it out! If you're able to successfully add a new method, you can create a pull request and we'll merge it in.

**Comment by cici-tan** [comment]
Thanks, I will try!

**Comment by bcyphers** [comment]
Please let us know if you come across any snags along the way. We want to make it as easy as possible for contributors to add new classifiers!

**Comment by cici-tan** [comment]
Sure I will tell you guys if so.

**Comment by micahjsmith** [comment]
This would be fulfilled by #113 which provides keras models

**Comment by micahjsmith** [comment]
Closing in favor of #113 issue.
