### ISSUE TITLE
update the field names in the modelhub database 

### ISSUE THREAD

**Issue by kveerama** [HDI-Project/ATM#58]
These are simple changes like error_msg --> error_message, model_path --> model_location, to more meaningful changes like tunables --> conditional_hyperparameters.

**Comment by kveerama** [comment]
These are simple changes like error_msg --> error_message, model_path --> model_location,  to more meaningful changes like tunables --> conditional_hyperparameters.

**Comment by bcyphers** [comment]
Some of this is addressed in #73.
