### ISSUE TITLE
Allow testing in other environments

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/ATM#6]
I'm guessing that the tester in their environment has populated the files `config/test/btb/aws.yaml` etc. and `data/car_1.csv` etc.

As it currently stands, it is not possible for someone who just clones the package to run tests and assure themselves the software is installed correctly/works correctly.

Consider overriding the .gitignore to commit the needed yaml and csv files for the test/ directory only? I imagine that the AWS tests would be skipped by default. Also, at the least, there could be unit tests for some of the software that are not dependent on data and configs.

(Somewhat unrelated to this issue, I would have thought that `test/method_test.py` does unit tests, and was going to recommend the more conventional `python -m pytest` invocation. But it seems that that file is very similar to `test/end_to_end_test.py`, doing end-to-end tests as well. Fairly confused by that.)

**Comment by bcyphers** [comment]
This should be addressed in #17
