### ISSUE TITLE
Include Matplotlib in 'requirements.txt'

### ISSUE THREAD

**Issue by alfredo-cuesta** [HDI-Project/ATM#67]
It would be nice that _matplotlib_  module was included in _requirements.txt_ too.
Sometimes it is useful in debugging tasks.

**Comment by bcyphers** [comment]
In #65, we will add multiple requirements files, including one for developers and one for testing. The development requirements file will include matplotlib, but we're going to leave it out of the main requirements file because it's not necessary to run the software.
