### ISSUE TITLE
Adding custom blocks to pipeline

### ISSUE THREAD

**Issue by kkarrancsu** [HDI-Project/ATM#71]
It would be nice to be able to add additional blocks to the ML pipeline, both static and dynamic (see #70 ).

**Comment by bcyphers** [comment]
The way I see it, there are two ways this could be done:

1. By adding dynamic steps before and after the actual model-training step which are subject to hyperparameters. This is already done to a certain extent with special hyperparameter keys like _PCA and _WHITEN. See the `Model.make_pipeline()` function in model.py. We could formalize and generalize this process and make it easier for users to apply other transformations to the data. Transformations applied in this manner would be computed once per classifier, and transformation hyperparameters could be optimized right along side of method hyperparameters. 

2. By adding static transformations at the Dataset level. For example, we could add options for dimensionality reduction or [deep feature synthesis](https://github.com/featuretools/featuretools) to the `create_dataset` function in enter_data.py. These transformations would be applied once at the time of dataset creation, the transformed data would be saved, and any dataruns which referenced the dataset would use the transformed data from the word go.

These two features could be built out separately, and I think in combination they'd give us most of what you are talking about.

**Comment by micahjsmith** [comment]
Relates to #113

**Comment by micahjsmith** [comment]
Closing in favor of #113 issue.
