### ISSUE TITLE
Got error while running 'python atm/enter_data.py'

### ISSUE THREAD

**Issue by kingmbc** [HDI-Project/ATM#78]
Hi all,
As a beginer of ATM,
I have below error while running 'python atm/enter_data.py', 
could you tell me how can I deal with this error?

Thank you!

=======================================
(myPy27) ubuntu@ip-172-31-17-79:~/workspace/git/atm$ python atm/enter_data.py
Traceback (most recent call last):
  File "atm/enter_data.py", line 8, in <module>
    from .config import *
ValueError: Attempted relative import in non-package

**Comment by bcyphers** [comment]
Hi, thanks for creating this issue. This is totally my fault, as a result of the pull request last Friday. I'll push a fix later tonight.

In the mean time, you should be able to get the script to work by running `pip install -e .` followed by `python -m atm.enter_data`. Likewise, to get the worker script to work you can run `python -m atm.worker`.

**Comment by bcyphers** [comment]
This has been addressed in a8cdadc65fa6299927ef64e95468effc62018cb2. The correct files to run are now in `scripts/enter_data.py` and `scripts/worker.py`. The command-line tooling logic has been removed from the files in `atm/`, and the README has been updated to reflect all this.

When you get a chance, try running
```
$ python scripts/enter_data.py
$ python scripts/worker.py
```
and make sure they work correctly.

**Comment by kingmbc** [comment]
@bcyphers Thank you!!
