### ISSUE TITLE
Bug in concatenating dataframes

### ISSUE THREAD

**Issue by kkarrancsu** [HDI-Project/ATM#83]
Hello,
I believe there is a bug in line 207 of atm/model.py   The call to concat should be as follows:

all_data = pd.concat([train_data, test_data])

See here: https://pandas.pydata.org/pandas-docs/version/0.20/generated/pandas.concat.html?highlight=concat#pandas.concat

I would submit a pull request but I have other changes and don't want to complicate things.

**Comment by bcyphers** [comment]
Good catch. I'll submit a pull request tonight.

Just FYI, I recently joined [EFF](https://github.com/EFForg/), and I'm no longer maintaining this project as my day job. I'll try to keep up with issues here, but I'll be a lot less responsive than I was.
