### ISSUE TITLE
Install failing 

### ISSUE THREAD

**Issue by ahgyger** [HDI-Project/ATM#9]
Seems that the install is conflicting with anaconda. Anyone found a work around? 

`
ahmets-MBP-782:atm ahmet$ virtualenv venv
Using base prefix '/Users/ahmet/anaconda'
New python executable in /Users/ahmet/Documents/GitHub/atm/venv/bin/python
dyld: Library not loaded: @rpath/libpython3.6m.dylib
  Referenced from: /Users/ahmet/Documents/GitHub/atm/venv/bin/python
  Reason: image not found
ERROR: The executable /Users/ahmet/Documents/GitHub/atm/venv/bin/python is not functioning
ERROR: It thinks sys.prefix is '/Users/ahmet/Documents/GitHub/atm' (should be '/Users/ahmet/Documents/GitHub/atm/venv')
ERROR: virtualenv is not compatible with this system or executable
`

**Comment by mirjalil** [comment]
I  am using anaconda as well. Instead of virtualenv I created an conda environment with python2.7:

`conda create -n atm27 python=2.7`

I also installed mysql separately (using brew for mac: `brew install mysql`)

Then the installation worked according to the rest of instructions.

**Comment by ahgyger** [comment]
Thanks @mirjalil, that helped moving forward. Will close.
