### ISSUE TITLE
Reorganize/clean-up requirements

### ISSUE THREAD

**Issue by csala** [HDI-Project/ATM#98]
Some requirements might not be needed, and dev and test distribution should be fixed.

An example of a misplaced requirements is tox, which is inside `requirements-dev.txt`

**Comment by micahjsmith** [comment]
Worth doing this, see https://github.com/DAI-Lab/cookiecutter-pypackage

**Comment by csala** [comment]
This was already covered in the [0.1.1 relase](/HDI-Project/ATM/tree/v0.1.1)
